### ISSUE TITLE
single quotes on windows

### ISSUE THREAD

**Issue by valtido** [isis97/atom-terminal-panel#12]
For some reason the \` is considered as single quote on windows, so now everytime I set variables, the terminal pops open and it's really annoying that I can't type the actual single quotes on editor

```
'`': 'atom-terminal-panel:toggle'
```

**Comment by isis97** [comment]
Changed ``` ` ``` to ``` ctrl + ` ```

**Comment by wizardfrag** [comment]
This also affects OS X, and makes this package completely and utterly unusable for me.

I fixed it by adding this to my keymap.cson:
```cson
'.platform-darwin atom-workspace':
  '`': 'unset!'
  'ctrl-`': 'atom-terminal-panel:toggle'
```

I'd rather not have to do this, though...
