### ISSUE TITLE
load project directory

### ISSUE THREAD

**Issue by nemonweb** [isis97/atom-terminal-panel#16]
sorry for my bad english

atom-terminal-panel not load opened project directory. Open home user directory. Please add terminal path like root directory. 

Thanks

**Comment by say2joe** [comment]
I agree that this is a huge problem. I'd like to create a custom command for multiple projects... but, can't get the currently opened project's (root) directory. Therefore, I can't cd into a variable project root directory.

**Comment by isis97** [comment]
Thanks for your suggestions. Now you can take advantage of the %(project.root), %(project.count) and even iterate the project directories using %(project:[index]) :)
