### ISSUE TITLE
Ability for adding commands to hotkeys

### ISSUE THREAD

**Issue by WebFreak001** [isis97/atom-terminal-panel#17]
I have added a command in the config to toolbar and now it would be nice if I could add a hotkey to that command like in the keymap.cson from atom.

**Comment by isis97** [comment]
Now you can create (in the `terminal-commands.json` file) atom commands, which calls the terminal, e.g:

```json
"actions": [
   ["name", "command to be executed in the terminal"]
]
```

And now bind it in your keymaps - it's now `atom-terminal-panel:name`. :D

**Comment by WebFreak001** [comment]
doesn't quite always execute the command then. Could be related to #20

**Comment by isis97** [comment]
The #20 bug was removed in the current release. Should work now.

**Comment by isis97** [comment]
Also note that you have to reload the window (by calling `reload` command or using the atom's window:reload) to make it work.
