### ISSUE TITLE
Object.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by yuuki-arc** [isis97/atom-terminal-panel#18]
Requiring `$` from `atom` is no longer supported.
If you are using `space-pen`, please require `$` from `atom-space-pen-views`. Otherwise require `jquery` instead:
  `{$} = require 'atom-space-pen-views'`
  or
  `$ = require 'jquery'`
Add `"atom-space-pen-views": "^2.0.3"` to your package dependencies.
Or add `"jquery": "^2"` to your package dependencies.
```
Object.Object.defineProperty.get (C:\Users\hoge\AppData\Local\atom\app-0.191.0\resources\app\exports\atom.js:48:11)
Object.<anonymous> (C:\Users\hoge\.atom\packages\atom-terminal-panel\lib\command-output-view.coffee:11:43)
```

**Comment by isis97** [comment]
The code was rewritten to use the newest atom api.
