### ISSUE TITLE
Default command prompt message

### ISSUE THREAD

**Issue by anobilisgorse** [isis97/atom-terminal-panel#2]
Is it just me, or from what I understood, the default command prompt message would be the EXACT PHRASE "%command%"? Or should it be the command message itself, like i.e. 
If I type the command "ls" -> "$> ls" ?

Correct me if I'm wrong, but is this a bug?

Please refer to this image to clarify:
![screenshot from 2015-02-05 02 58 22](https://cloud.githubusercontent.com/assets/8383878/6047168/e165fa70-ace2-11e4-966b-2dd2bd52802c.png)

Thanks in advance.

**Comment by isis97** [comment]
Sorry, but the default command prompt value is invalid. (the %command% is unsupported, old variable annotation, which makes no sense). I will repair all broken default values in next 12 hours. Thanks for reporting that issue.

The command prompt always looks that: user  defined_command_prompt command:
So you can try e.g:
%(label:badge:text:%(line)) %(hours):%(minutes) $.../%(path:-2)/%(path:-1)> 
This creates badge with line number, then hours, minutes, dollar character and tree dots and then two last components for the current working directory.

You can also use css/html e.g <b>%(line)</b> any text >

**Comment by anobilisgorse** [comment]
Thank you for that. Seen the update and it was quite great too. :)

Although I would like to know how to include my previous input to the command prompt message, just like in the Terminal. 

![rsz_screenshot_from_2015-02-07_184138](https://cloud.githubusercontent.com/assets/8383878/6091826/3356bbfe-aef9-11e4-817f-099b4521c5b0.jpg)

Just like that, you know. The user + computer name. then after I've entered a command it would be appended. Well you gave me the idea for the time so I'd like to append it too, but I wish I could convert it to an AM/PM 12 hour-mode.

Sorry for the hassle, but I appreciate it if you could give me the variable/code snippet for the user and computer name, %(user) and %(computer-name) doesn't work. And if it is possible, the time in 12 hour mode too. Thanks. :)
