### ISSUE TITLE
Command to Disable Suggesstion? 

### ISSUE THREAD

**Issue by louisgv** [isis97/atom-terminal-panel#24]
Is there anyway I can disable the suggestion with just a command or a config file? Currently I can only disable it by changing the source.

The current suggestion is very distracting as the cursor got moved out of range every time it appears:

![screenshot 106](https://cloud.githubusercontent.com/assets/6723574/7440188/c3647808-f058-11e4-977b-eb6fb81b5ff2.png)

The best way to implement suggestion imo, is similar to gnome-terminal where pressing TAB ask user whether they want to see all command or not, and list them afterward.

**Comment by isis97** [comment]
Now there's key for enabling the autocompletion (atom-terminal-panel:toggle-autocompletion) - in v.4.4.4
Thanks for your suggestion. :+1:
