### ISSUE TITLE
Conflicting CTRL Key

### ISSUE THREAD

**Issue by monotykamary** [isis97/atom-terminal-panel#37]
Reproduce: 
1. Open terminal
2. Do anything and close/exit terminal
3. Press CTRL -> Terminal opens
4. Loss in sales revenue 

Please, do not ever use CTRL to open up the pop-up command menu. Whenever I press CTRL, it opens up the terminal and often inhibits keybindings, especially splitting tabs and copy pasterino.

EDIT: only way to stop it is to close the terminal through ESC

**Comment by allysonsouza** [comment]
:+1:

**Comment by gaurav21r** [comment]
+1 @isis97  Any update on this! ?

**Comment by JavascriptIsMagic** [comment]
I found a way to change this (probably not intended way)
Here is a visual aid: http://i.imgur.com/Pv4tsWW.png
I went in and edited the source code in `atom-terminal-panel/keymaps/atp.cson`
changed the keymaps to something other then just `ctrl`
saved and closed atom editor and opened it again
This seams to remap these keybindings to whatever you want, I don't know if atom has some sort of intended way to remap these though, I know this is not an ideal solution.

**Comment by batjko** [comment]
I just found this as well.
However, only after pressing the exit button, not after pressing the close button.
I guess the command that waits for `toggle-autocompletion` is left over after `exit` is triggered, but not after `close`?

![http://i.imgur.com/MDsr7LS.gif](http://i.imgur.com/MDsr7LS.gif)

**Comment by batjko** [comment]
This is really becoming a major nuisance to me. Every time after using the panel once, the likelihood that the terminal keeps coming up every time I press Ctrl is close to 100%. 
It's an awesome package, but this is like the Coolaid man breaking through the wall three times per minute while I am trying to work.

I'd rather not switch to a different terminal package again, so just checking if anybody is working on this?

**Comment by batjko** [comment]
Hi,

I'm not sure what others see, but the issue persists.
Still the exact same behavior.

Was the new version of the package not published, perhaps?

**Comment by jeremyramin** [comment]
@batjko Yeah, the changes have been applied to the repository but they haven't been released as a new package version yet.

**Comment by victorsj1** [comment]
I just uninstalled and disabled atom-terminal panel. Got really sick of it. Whoever created that package kind of didn't give a daymn about programmer productivity.
