### ISSUE TITLE
Navigate previously entered commands

### ISSUE THREAD

**Issue by anobilisgorse** [isis97/atom-terminal-panel#4]
Sorry once again, but may I ask if a feature like in the Terminal exists here where you could browse your previously entered commands? Such thing is a hassle if ever I type a "test" command and the length of the command is very long (due to the location of the tested file in the directory) to be typed again.

Or would it be a future feature to be expected in new releases? Much thanks. :)

**Comment by isis97** [comment]
I's pretty done, so you can expect that I will release soon a new version which will support arrow keys navigation.

**Comment by rober423** [comment]
This feature needs work. As far as I can tell it only stores a limited few of your previous commands. And, perhaps as a consequence to that, navigating them with up and down arrows appears out-of-order. maybe they are looping when they are not supposed to?

For example I press up once, and cannot press up so then I press down. I would expect this to take me to a blank command where I cannot go down further. Instead I am taken to the command I wrote two lines ago and can continue backwards in history by pressing down, but only for 8 commands worth. and some seem missing where there is instead another line of my last written command? History should transverse by pressing the up arrow, not the down, and I shouldn't have to delete text to get back to a blank line. A history log command may also be helpful.
