### ISSUE TITLE
%(editor.name) behaves differently on OS X and Windows

### ISSUE THREAD

**Issue by blah-blah** [isis97/atom-terminal-panel#53]
On Windows, `%(editor.name)` gives the name of the file in the currently open editor tab, e.g., `filename.txt`. In OS X, the same variable gives the full path to the file, e.g., `path/to/filename.txt`. Possible bug?

I'm using atom-terminal-panel 4.4.4.

**Comment by jeremyramin** [comment]
The next update should fix this. At the very least, I'm on OS X right now and it works fine.
