### ISSUE TITLE
Ability to get basename without extension

### ISSUE THREAD

**Issue by blah-blah** [isis97/atom-terminal-panel#54]
Is it possible to get the basename without the extension of the currently opened file with any of the variables currently in atom-terminal-panel? (That is, `filename` from `path/to/filename.txt`)

**Comment by IrksomeZeus** [comment]
I don't think that there are any builtin variables that will do this but you can add something like
```CoffeeScript
"name":
    "description": "Displays current filename without extension."
    "variable": (state) -> return state.getCurrentFileName().replace /\.[a-z]+/g, ''
```
to one of the command files or create your own - I put it under utils. These are in atom-terminal-panel/commands. Then whenever you enter %(name) it will be replaced with the filename without the extension

**Comment by blah-blah** [comment]
Thanks, that's very helpful.

**Comment by blah-blah** [comment]
I believe the regex in the code above replaces all occurrences of the "." character in the file path. This could be a problem. The following just replaces the last occurrence:

```
  "name":
    "description": "Displays current filename without extension."
    "variable": (state) -> return state.getCurrentFileName().replace /\.([a-z]+)$/, ''
```

(I think.)
