### ISSUE TITLE
mkdir newfolder

### ISSUE THREAD

**Issue by garfieldbanks** [isis97/atom-terminal-panel#81]
Warning! Failed to create directory Error: EPERM: operation not permitted, mkdir 'C:\Windows\system32\newfolder'

The command "mkdir newfolder" should attempt to create "newfolder" in the current listed directory. Right now I have type "mkdir .\newfolder" to get it to work.

**Comment by estebangallego** [comment]
Hello everyone. I'm having the same issue.
<img width="1005" alt="screen shot 2016-01-28 at 8 55 38 pm" src="https://cloud.githubusercontent.com/assets/5769433/12667521/951be47a-c601-11e5-9eb4-8b4d06697230.png">
